;; -*- mode: eask; lexical-binding: t -*-

(package "ox-nippou"
         "1.0.0"
         "Export nippou from org-mode file")

(website-url "https://github.com/mugijiru/ox-nippou")
(keywords "tools" "docs")

(package-file "ox-nippou.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "30.1")
(depends-on "org" "9.7")
(depends-on "markdown-mode" "2.5")
